name: Release
on:
  push:
    branches:
      - main # set your default branch

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release by DX Heroes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - uses: dxheroes/gh-action-auto-release@v1
        with:
          release-type: node
          package-name: masspay-js-sdk
          extra-files: |
            README.md
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}