name: Release
on:
  push:
    branches:
      - main # set your default branch

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release by DX Heroes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dxheroes/gh-action-auto-release@v1.0.0
        with:
          release-type: node
          package-name: masspay-js-sdk
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}